// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMMJzMKN9F0AqV-rw4qUtZUIJAtTOd54',
    appId: '1:561145579318:web:b8516e0f53e234bb165597',
    messagingSenderId: '561145579318',
    projectId: 'swifttaskapp',
    authDomain: 'swifttaskapp.firebaseapp.com',
    storageBucket: 'swifttaskapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIguYrL_7AJoaoIZAnvfYPVIWsoNWLhyk',
    appId: '1:561145579318:android:ca2ffa239dfb79a1165597',
    messagingSenderId: '561145579318',
    projectId: 'swifttaskapp',
    storageBucket: 'swifttaskapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT_JUYdN3jMC_kLNkwNvMkvWd8L0DUZw',
    appId: '1:561145579318:ios:7dcd0f58c530cc93165597',
    messagingSenderId: '561145579318',
    projectId: 'swifttaskapp',
    storageBucket: 'swifttaskapp.appspot.com',
    iosClientId: '561145579318-tl5gfao1i6h977dto1pi0ip4sh2ncgva.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamSwifttask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCT_JUYdN3jMC_kLNkwNvMkvWd8L0DUZw',
    appId: '1:561145579318:ios:7dcd0f58c530cc93165597',
    messagingSenderId: '561145579318',
    projectId: 'swifttaskapp',
    storageBucket: 'swifttaskapp.appspot.com',
    iosClientId: '561145579318-tl5gfao1i6h977dto1pi0ip4sh2ncgva.apps.googleusercontent.com',
    iosBundleId: 'com.example.jamSwifttask',
  );
}
